"use client";
import Navbar from "../../components/Navbar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { BusinessProvider } from '../../../context/BusinessContext';
import { useParams } from 'next/navigation';

const { businessId } = useParams();

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <BusinessProvider businessId={businessId as string}>
          <Navbar />
          {children}
        </BusinessProvider>
      </body>
    </html>
  );
}
